defenseunicorns/uds-package-gitlab-runner

values/registry1-values.yaml
values/upstream-values.yaml

Because Pepr mutates container security contexts if the user / group is not set, is set to 0, or is set to user name not uid, some pipeline jobs fail.
For example, the cosign component uses the chainguard cosign image which runs as user `nonroot`. Pepr sees this and mutates the user to `1000`. This causes issues when cosign then tries to write to the container. 
none
Use `uds/user` and `uds/group` as runner pod labels that can be set by CI variable per job in the `.gitlab-ci.yml` to ensure build containers run as the expected user. In case of images running as root, try to find alternative nonroot images. For cases in which the user must be root, a Pepr exemption must be made.

fix: build container security context

---

.github/workflows/commitlint.yaml

Adds `milestoned` to the pr type on commitlint action to facilitate kicking of ci for required checks on release please PRs
Fixes #
Relates to #

ci: add milestoned to commitlint workflow to enable ci on release

---

tasks.yaml
tasks/create.yaml
tasks/deploy.yaml
tasks/publish.yaml
tasks/test.yaml

fix unvendored kubectl and zarf commands
remove no longer valid--no-progress flag
Fixes #
Relates to #

chore: fix unvendored kubectl and zarf, remove --no-progress flag

---

tasks/publish.yaml

This fixes the publish task to properly use `-a` to pass architecture into `uds-cli`.  Relevant run with uds-cli v0.9.3 on an amd system:
Fixes #51

fix: architecture issues in nested `uds-cli` publish

---

.github/workflows/test.yaml

reduce runner to 8 core since gitlab deployment has been scaled down for ci

ci: reduce size of runner

---

.github/workflows/test.yaml
tasks.yaml

This fixes upgrade tests not actually running due to a malformed input.
Fixes #N/A

chore: hotfix upgrade test action

---

renovate.json

Adds a renovate schedule to the repo to avoid paid runner churn
Fixes #N/A

chore: add a renovate schedule to reduce paid runner churn

---

tasks.yaml

This fixes the latest release bundle to use the uds-common spoof.
Fixes #N/A

chore: hotfix the update to spoof the release

---

test/common.ts
test/journey/pipeline-run.test.ts
test/journey/registration.test.ts

This improves the patterns for running jest tests for GLR - we decided against cypress and playwright because both run the tests in browser and cannot make use of spawnSync or KFC.
Fixes #72

chore: improve jest test patterns

---

chart/templates/clusterrole.yaml
chart/templates/namespace.yaml
chart/templates/rolebinding.yaml
chart/templates/uds-package-sandbox.yaml
chart/templates/uds-package.yaml
chart/values.yaml
tasks.yaml
tasks/publish.yaml
values/common-values.yaml
values/config-values.yaml

feat!: add netpols and monitoring

---

common/zarf.yaml

Adds a wait action for the GLR package CR. This is consistent with the pattern in uds-core however it runs after the GitLab Runner chart installs (meaning the GitLab Runner chart may still fail waiting on resources like secrets to exist) however this will catch other issues such as failed updates to resources or missing resources the chart doesn't directly depend on like netpols.
Fixes #N/A

feat: add wait for GLR package CR readiness

---

values/registry1-values.yaml
values/upstream-values.yaml

Fixes renovate being able to detect the Helm values now that they use `###ZARF_REGISTRY###`
Fixes #N/A

chore: fix renovate config for gitlab runner sandbox images

---

adr/0002-zarf-agent-ignore-sandbox-namespace.md

This adds an ADR for the GitLab runner sandbox Zarf agent ignore setting.
Fixes #99

chore: add an ADR for the GitLab runner sandbox Zarf agent ignore setting

---

common/zarf.yaml
zarf.yaml

This moves the variables to the root from common
Fixes #N/A

chore: move the variables from common to root for discoverability

---

chart/templates/plugin-registry.yaml

This downgrades the DestinationRule in GLR's fleeting config since it will not run on older clusters.
Fixes #N/A

fix: downgrade destination rule to support older clusters

---

tasks.yaml

Fixes the ifs since there is no proper GitLab arm64.
Fixes #N/A

chore: fix arm64 'if's for release

---

.github/workflows/nightly-testing.yaml

jumpbox was missing socat which causes nightly pipeline to fail

fix: install socat in jumpbox

---

chart/templates/plugin-registry.yaml
chart/values.yaml
values/common-values.yaml

This improves Helm value flexibility by:
1. Allowing the plugin registry image to be overridden
2. Removing deprecated values from the main chart
Fixes #N/A

chore: improve helm value flexibility

---

values/common-values.yaml

This defaults the registry URL to use the correct namespace by default and allow templating it
Fixes #N/A

fix: default the registry URL to use the correct namespace by default

---

chart/templates/clusterrole.yaml
chart/templates/namespace.yaml
chart/templates/rolebinding.yaml
chart/templates/uds-package-sandbox.yaml
chart/templates/uds-package.yaml
chart/templates/uds-policy-exemptions.yaml
chart/values.yaml
docs/configuration.md
values/common-values.yaml
values/config-values.yaml

- Updating all instances of custom: [] to additionalNetworkAllow: []
> [!CAUTION]
> **BREAKING CHANGE** `custom` has changed to `additionalNetworkAllow` and sandbox namespace values have been moved under `kubernetesSandbox`
Fixes #
Relates to #
https://github.com/orgs/defenseunicorns/projects/118/views/12?pane=issue&itemId=87152090&issue=defenseunicorns%7Cuds-package-maintenance%7C5

chore!: update custom network properties key

---

tests/journey/pipeline-run.test.ts

Updates the create repo step in the tests to avoid CI flakes like this: https://github.com/defenseunicorns/uds-package-gitlab-runner/actions/runs/12310536916/job/34359271705
Fixes #N/A

chore: update test to ensure git config setup

---

chart/templates/plugin-registry.yaml
releaser.yaml

An update in the underlying registry image used in the plugin registry changed the config file path and that broke the registry serve command. This PR updates the config file passed to the serve command to the correct location
Fixes #
Relates to #

fix: fix plugin registry

---

chart/templates/plugin-registry.yaml
chart/templates/uds-package.yaml
docs/configuration.md
values/common-values.yaml

Docker Autoscaler: https://docs.gitlab.com/runner/executors/docker_autoscaler/ 
It wraps the [Docker executor](https://docs.gitlab.com/runner/executors/docker/) so that all Docker executor options and features are supported.
This builds on top of the existing 'instance' executor configurations. 
Fixes #
Relates to #

chore: adding support for docker autoscaler

---

chart/templates/plugin-registry.yaml
chart/values.yaml
releaser.yaml

Updates the template for the Plugin Registry deployment to allow user to configure the imagePullPolicy, and sets the policy to `Always` by default.  Additionally allows users to opt out of deploying the plugin registry in the event they are using a fleeting plugin that is not included in the plugin registry image.
Fixes #177

fix: default imagePullPolicy for Plugin Deployment to Always

---

chart/templates/rolebinding.yaml
chart/values.yaml
releaser.yaml

Currently the [namespace](https://github.com/defenseunicorns/uds-package-gitlab-runner/blob/main/chart/templates/rolebinding.yaml) used by the ClusterRoleBinding resource is hardcoded to be `gitlab-runner`.  In situations where multiple runners are desired, this namespace will be unique per deployment of this package, so we must allow users to determine which namespace contains the service account that will be creating resources in the sandbox namespace.  Not doing this results in immediately job failures as the scheduler pod cannot perform any actions in the sandbox namespace.
Fixes #
Relates to #

fix: configurable rbac namespace

---

values/common-values.yaml

- add templating for extra `[runners.docker]` options via `runners.fleeting.docker_extra_config` value
- confirmed templating works correctly with no value ( `{}` default) and when a value is passed
- make indentation consistent and correct

feat: add templating for extra runners.docker options, make indentation consistent

---

values/upstream-values.yaml
zarf.yaml

Updated the renovate comment extractVersion that isnt working to match the one in releaser.yaml that is working (remove extra `\`)

chore: attempt to fix broken renovate comments

---

releaser.yaml
values/common-values.yaml

Explicitly cast runners.autoscaler.connector_config.protocol_port as int as toToml makes it a float. This behavior is not new, but gitlab runner 18.x now strictly enforces type. Passing as a string results in a similar error.
```
Merging configuration from template file "/configmaps/config.template.toml" 
FATAL: Could not handle configuration merging from template file  error=couldn't load configuration template file: decoding configuration file: toml: line 31 (last key "runners.autoscaler.connector_config.protocol_port"): incompatible types: TOML value has type float64; destination has type integer
```
Built and deployed package locally with change and confirmed it resolves the issue observed.

fix: update autoscaler runner templating
